# Generated by Django 6.0.4 on 2026-04-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_created_at_alter_saved_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saved",
            name="content",
        ),
    ]
