# Generated by Django 6.0.4 on 2026-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_address_customuser_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("buyer", "XARIDOR"), ("seller", " SOTUVCHI")],
                default="buyer",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tg_username",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
