# Generated by Django 6.0.4 on 2026-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
