# Generated by Django 6.0.4 on 2026-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
